local palettes = {
  day = {
    bg = "#d0d5e3",
    fg = "#a8aecb",
    black = "#b4b5b9",
    blue = "#2e7de9",
    blue0 = "#7890dd",
    blue1 = "#188092",
    cyan = "#007197",
    error = "#c64343",
    gray = "#6172b0",
    green = "#587539",
    green_bright = "#387068",
    magenta = "#9854f1",
    orange = "#b15c00",
    purple = "#7847bd",
    red = "#f52a65",
    teal = "#118c74",
    yellow = "#8c6c3e",
  },
  moon = {
    bg = "#1e2030",
    fg = "#3b4261",
    black = "#1b1d2b",
    blue = "#82aaff",
    blue0 = "#3e68d7",
    blue1 = "#65bcff",
    cyan = "#86e1fc",
    error = "#c53b53",
    gray = "#828bb8",
    green = "#c3e88d",
    green_bright = "#4fd6be",
    magenta = "#c099ff",
    orange = "#ff966c",
    purple = "#fca7ea",
    red = "#ff757f",
    teal = "#4fd6be",
    yellow = "#ffc777",
  },
  night = {
    bg = "#16161e",
    fg = "#3b4261",
    black = "#15161e",
    blue = "#7aa2f7",
    blue0 = "#3d59a1",
    blue1 = "#2ac3de",
    cyan = "#7dcfff",
    error = "#db4b4b",
    gray = "#a9b1d6",
    green = "#9ece6a",
    green_bright = "#73daca",
    magenta = "#bb9af7",
    orange = "#ff9e64",
    purple = "#9d7cd8",
    red = "#f7768e",
    teal = "#1abc9c",
    yellow = "#e0af68",
  },
  storm = {
    bg = "#1f2335",
    fg = "#3b4261",
    black = "#1d202f",
    blue = "#7aa2f7",
    blue0 = "#3d59a1",
    blue1 = "#2ac3de",
    cyan = "#7dcfff",
    error = "#db4b4b",
    gray = "#a9b1d6",
    green = "#9ece6a",
    green_bright = "#73daca",
    magenta = "#bb9af7",
    orange = "#ff9e64",
    purple = "#9d7cd8",
    red = "#f7768e",
    teal = "#1abc9c",
    yellow = "#e0af68",
  },
}
return {
  setup = function(_, flavor)
    flavor = flavor or "moon"
    local colors = palettes[flavor]
    return {
    section_separator = { open = "", close = "" },
    part_separator = { open = "", close = "" },
    inverse_separator = { open = "", close = "" },

    style_a = {
      fg = colors.black,
      bg_mode = { normal = colors.blue, select = colors.magenta, un_set = colors.red },
    },
    style_b = {
      fg = colors.blue,
      bg = colors.fg,
    },
    style_c = {
      fg = colors.fg,
      bg = colors.bg,
    },

    permissions_t_fg = colors.blue,
    permissions_r_fg = colors.blue1,
    permissions_w_fg = colors.purple,
    permissions_x_fg = colors.green,
    permissions_s_fg = colors.error,

    selected = { icon = "󱊅 ", fg = colors.magenta },
    copied = { icon = "󰆏 ", fg = colors.blue0 },
    cut = { icon = "󰆐 ", fg = colors.red },

    total = { icon = "󰆙 ", fg = colors.magenta },
    succ = { icon = "󰄸 ", fg = colors.green },
    fail = { icon = "󰱝 ", fg = colors.red },
    found = { icon = "󰩉 ", fg = colors.blue },
    processed = { icon = "󱊆 ", fg = colors.green },
  }
  end,
}
