# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio = [1, 4, 3]
sort_by = "alphabetical"
sort_sensitive = false
sort_reverse = false
sort_dir_first = false
linemode = "none"
show_hidden = true
show_symlink = true
scrolloff = 5

[preview]
tab_size = 2
max_width = 600
max_height = 900
cache_dir = ""
image_filter = "triangle"
image_quality = 75
sixel_fraction = 15
ueberzug_scale = 1
ueberzug_offset = [0, 0, 0, 0]

[opener]
edit = [
  { run = 'nvim "$@"', block = true, for = "unix" },
  { run = 'code "%*"', orphan = true, for = "windows" },
]
open = [
  { run = 'xdg-open "$@"', desc = "Open", for = "linux" },
  { run = 'open "$@"', desc = "Open", for = "macos" },
  { run = 'start "" "%1"', orphan = true, desc = "Open", for = "windows" },
]
reveal = [
  { run = 'open -R "$1"', desc = "Reveal", for = "macos" },
  { run = 'explorer /select, "%1"', orphan = true, desc = "Reveal", for = "windows" },
  { run = '''exiftool "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show EXIF", for = "unix" },
]
extract = [
  { run = 'unar "$1"', desc = "Extract here", for = "unix" },
  { run = 'unar "%1"', desc = "Extract here", for = "windows" },
]
play = [
  { run = 'mpv "$@"', orphan = true, for = "unix" },
  { run = 'mpv "%1"', orphan = true, for = "windows" },
  { run = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info", for = "unix" },
]

[open]
rules = [
  { name = "*/", use = [
    "open",
    "edit",
    "reveal",
  ] },

  { mime = "text/*", use = [
    "edit",
    "reveal",
  ] },
  { mime = "image/*", use = [
    "open",
    "reveal",
  ] },
  { mime = "video/*", use = [
    "play",
    "reveal",
  ] },
  { mime = "audio/*", use = [
    "play",
    "reveal",
  ] },
  { mime = "inode/x-empty", use = [
    "edit",
    "reveal",
  ] },

  { mime = "application/json", use = [
    "edit",
    "reveal",
  ] },
  { mime = "*/javascript", use = [
    "edit",
    "reveal",
  ] },

  { mime = "application/zip", use = [
    "extract",
    "reveal",
    "archive",
  ] },
  { mime = "application/gzip", use = [
    "extract",
    "reveal",
    "archive",
  ] },
  { mime = "application/x-tar", use = [
    "extract",
    "reveal",
    "archive",
  ] },
  { mime = "application/x-bzip", use = [
    "extract",
    "reveal",
    "archive",
  ] },
  { mime = "application/x-bzip2", use = [
    "extract",
    "reveal",
    "archive",
  ] },
  { mime = "application/x-7z-compressed", use = [
    "extract",
    "reveal",
    "archive",
  ] },
  { mime = "application/x-rar", use = [
    "extract",
    "reveal",
    "archive",
  ] },
  { name = "*", use = [
    "open",
    "reveal",
  ] },
]

[plugin]
prepend_previewers = [
  { name = "*.md", run = "glow" },
  { mime = "audio/*", run = "exifaudio" },
  { name = "*/", run = "eza-preview" },
]
